-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4j+ayMZBiEHMxk2g
0pEEb1leqK/1I+kRTR9ZY/6dIqKgCgYIKoZIzj0DAQehRANCAAREDxgFdwK4Ugxx
0q1imGuuhgiV5AaHQctjG7H1opxUnr6yG9Xi+lACM5wWWQILJKOI7OyZRtQu9XlB
5cHnPasV
-----END PRIVATE KEY-----