-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg5R2sZhTfZp8Jtjbc
04+kdeWdotmNYqEDuFgPhVhKYXqgCgYIKoZIzj0DAQehRANCAAT7FLLrzKyzJQud
0OTMllNcwCK0mhZbgsmCENnexHfM/+NHDD7k8tt+wj4aBHyVukVQCYPedf9QwQ4u
yvU53qHq
-----END PRIVATE KEY-----