server:
  port: 8080

# spring config
spring:
  config:
    activate:
      on-profile: "prod"

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true



# prometheus config
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# security config
security:
  jwt:
    token:
      validtime:
        access: 21600000
        refresh: 2073600000
      secretkey: ${TOKEN_SECRETKEY}
  cors:
    path-patterns: ${CORS_PATH_PATTERNS}
    origin-patterns: ${CORS_ORIGIN_PATTERNS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    exposed-headers: ${CORS_EXPOSED_HEADERS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
    max-age: ${CORS_MAX_AGE}

# cookie config
cookie:
  domain: ${COOKIE_DOMAIN}
  path: ${COOKIE_PATH}
  max-age: ${COOKIE_MAX_AGE}

# api docs config
springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger


apple:
  team-id: ${APPLE_TEAM_ID}
  login-key: ${APPLE_LOGIN_KEY}
  client-id: ${APPLE_CLIENT_ID}
  redirect-url: ${APPLE_REDIRECT_URL}
  key-path: ${APPLE_KEY_PATH}
  oauth-uri : ${APPLE_OAUTH_URI}

kakao:
  host: https://kauth.kakao.com
  adminKey: adminKey
  uri:
    token: https://kauth.kakao.com/oauth/token
    token_info: https://kapi.kakao.com/v1/user/access_token_info
    me_info: https://kapi.kakao.com/v2/user/me
    unlink: https://kapi.kakao.com/v1/user/unlink
  redirect_uri: http://localhost:8080/api/v1/social/kakao
  client_id: thisIsKaKaoClientId



client:
  max-attempts: 3
  pool:
    max-connect: 100
    max-connect-per-route: 5
  timeout:
    connect: 5000
    read: 5000
  retry:
    maxAttempts: 3
    backOffPeriod: 2000
