server:
  port: 8080

# spring config
spring:
  config:
    activate:
      on-profile: "prod"

  data:
    mongodb:
      uri: ${MONGODB_URI}



# prometheus config
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# security config
security:
  jwt:
    token:
      validtime:
        access: 21600000
        refresh: 2073600000
      secretkey: ${TOKEN_SECRETKEY}
  cors:
    path-patterns: ${CORS_PATH_PATTERNS}
    origin-patterns: ${CORS_ORIGIN_PATTERNS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    exposed-headers: ${CORS_EXPOSED_HEADERS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
    max-age: ${CORS_MAX_AGE}

# cookie config
cookie:
  domain: ${COOKIE_DOMAIN}
  path: ${COOKIE_PATH}
  max-age: ${COOKIE_MAX_AGE}

# api docs config
springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger


apple:
  team-id: ${APPLE_TEAM_ID}
  login-key: ${APPLE_LOGIN_KEY}
  client-id: ${APPLE_CLIENT_ID}
  redirect-url: ${APPLE_REDIRECT_URL}
  key-path: ${APPLE_KEY_PATH}
  oauth-uri : ${APPLE_OAUTH_URI}


