server:
  port: 8080

# spring config
spring:
  config:
    activate:
      on-profile: "local"


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50

api:
  datasource:
    jdbc-url: jdbc:mysql://localhost:13306/api?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# logging config
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# prometheus config
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# security config
security:
  jwt:
    token:
      validtime:
        access: 31557600000
        refresh: 31557600000
      secretkey: jwtsecretKeyhastolonghowlongidontknow
  cors:
    path-patterns: "/**"
    origin-patterns: "http://localhost:3000"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Set-Cookie, Authorization, Content-Type, X-Requested-With, Accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin, Access-Control-Allow-Credentials"
    allow-credentials: true
    max-age: 1800

# cookie config
cookie:
  domain: localhost
  path: /
  max-age: 86400

# api docs config
springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger
